language: java
os: linux
jdk:
    - openjdk8
script:
    - mvn test -DargLine="-Dcontiperf.active=false"

branches:
    only:
        - development_junit
    except:
        - master
        - development
